### ISSUE TITLE
Issue with demo install & sandbox

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/biocache-service#11]
2014-12-12 07:52:28,330 [LocationProcessor] Problem processing using the SDS for record drt0|02663a3b-1d09-4b19-91bf-64e7a9e07a0f
java.lang.NullPointerException
        at au.org.ala.sds.model.SensitivityInstance.equals(SensitivityInstance.java:89)
        at java.util.ArrayList.indexOf(ArrayList.java:298)
        at java.util.ArrayList.contains(ArrayList.java:281)
        at au.org.ala.sds.model.SensitiveTaxonStore.verifyAndInitialiseSpeciesList(SensitiveTaxonStore.java:106)
        at au.org.ala.sds.model.SensitiveTaxonStore.<init>(SensitiveTaxonStore.java:58)
        at au.org.ala.sds.SensitiveSpeciesFinderFactory.getStoreFromUrl(SensitiveSpeciesFinderFactory.java:103)
        at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:61)
        at au.org.ala.sds.SensitiveSpeciesFinderFactory.getSensitiveSpeciesFinder(SensitiveSpeciesFinderFactory.java:44)
        at au.org.ala.biocache.Config$.sdsFinder$lzycompute(Config.scala:68)
        at au.org.ala.biocache.Config$.sdsFinder(Config.scala:66)
        at au.org.ala.biocache.processor.LocationProcessor.sdsFinder$lzycompute(LocationProcessor.scala:33)
        at au.org.ala.biocache.processor.LocationProcessor.sdsFinder(LocationProcessor.scala:33)
        at au.org.ala.biocache.processor.LocationProcessor.processSensitivity(LocationProcessor.scala:823)
        at au.org.ala.biocache.processor.LocationProcessor.process(LocationProcessor.scala:125)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:96)
        at au.org.ala.biocache.processor.RecordProcessor$$anonfun$processRecord$1.apply(RecordProcessor.scala:95)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:206)
        at au.org.ala.biocache.processor.Processors$.foreach(Processors.scala:10)
        at au.org.ala.biocache.processor.RecordProcessor.processRecord(RecordProcessor.scala:95)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:332)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1$$anonfun$applyOrElse$1.apply(ProcessRecords.scala:327)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
        at au.org.ala.biocache.tool.Consumer$$anonfun$act$1$$anonfun$apply$1.applyOrElse(ProcessRecords.scala:327)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply$mcVL$sp(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:33)
        at scala.runtime.AbstractPartialFunction$mcVL$sp.apply(AbstractPartialFunction.scala:25)
        at scala.actors.ReactorTask.run(ReactorTask.scala:31)
        at scala.actors.Reactor$class.resumeReceiver(Reactor.scala:129)
        at au.org.ala.biocache.tool.Consumer.scala$actors$InternalReplyReactor$$super$resumeReceiver(ProcessRecords.scala:303)
        at scala.actors.InternalReplyReactor$class.resumeReceiver(InternalReplyReactor.scala:59)
        at au.org.ala.biocache.tool.Consumer.resumeReceiver(ProcessRecords.scala:303)
        at scala.actors.InternalActor$class.searchMailbox(InternalActor.scala:76)
        at au.org.ala.biocache.tool.Consumer.searchMailbox(ProcessRecords.scala:303)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(Reactor.scala:117)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
        at scala.actors.Reactor$$anonfun$startSearch$1$$anonfun$apply$mcV$sp$1.apply(Reactor.scala:114)
        at scala.actors.ReactorTask.run(ReactorTask.scala:33)
        at scala.actors.ReactorTask.compute(ReactorTask.scala:63)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by djtfmartin** [comment]
closing. cant reproduce
