### ISSUE TITLE
StringIndexOutOfBoundsException in SearchDAOImpl.runSolrQuery

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#142]
The following stacktrace shows up in the logs on biocache-b3:

```
2017-02-21 14:25:41,639 [org.ala.biocache.dao.SearchDAOImpl] Error executing query with requestParams: q=lsid:http://id.biodiversity.org.au/node/apni/2913682&fq=collection_uid:"co12"&fq=state_conservation:"&fq=data_hub_uid:dh2&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=data_hub_uid:dh2&facets=taxon_name&f
acets=raw_taxon_name&facets=kingdom&facets=phylum&facets=class&facets=order&facets=family&facets=genus&facets=species&facets=subspecies_name&facets=rank&facets=name_match_metric&facets=species_group&facets=raw_identification_qualifier&facets=taxonomic_issue&facets=original_name_usage&facets=collector&facets=establish
ment_means&facets=month&facets=year&facets=occurrence_decade_i&facets=state_conservation&facets=country&facets=cl927&facets=cl20&facets=cl1048&facets=cl21&facets=cl966&facets=cl1918&facets=cl617&facets=cl620&facets=cl958&facets=cl1049&facets=cl916&facets=uncertainty&facets=coordinate_uncertainty&facets=geospatial_kos
her&facets=sensitive&facets=assertions&facets=outlier_layer&facets=outlier_layer_count&facets=user_assertions&facets=assertion_user_id&facets=duplicate_status&facets=duplicate_type&facets=collection_uid&facets=raw_datum&flimit=10&formattedQuery=lft:[506164 TO 506194]&facet=true EXCEPTION: String index out of range: -
1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1911)
        at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2576)
        at au.org.ala.biocache.dao.SearchDAOImpl.findByFulltextSpatialQuery(SearchDAOImpl.java:700)
        at au.org.ala.biocache.dao.SearchDAOImpl.findByFulltextSpatialQuery(SearchDAOImpl.java:676)
        at sun.reflect.GeneratedMethodAccessor469.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
        at com.sun.proxy.$Proxy36.findByFulltextSpatialQuery(Unknown Source)
        at au.org.ala.biocache.web.OccurrenceController.occurrenceSearch(OccurrenceController.java:675)
        at sun.reflect.GeneratedMethodAccessor466.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:193)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ansell** [comment]
The line numbers don't exactly match with the current master, but it could be the following lines causing it, as they do not check the split string's length before calling substring on parts[0]:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/8cf5de4094ae08648b9a985fa22f0c4a906adec0/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L2578

```
                        if (parts[0].startsWith("-")) {
prefix = "-" + ClientUtils.escapeQueryChars(parts[0].substring(1));
```
