### ISSUE TITLE
Error when requesting elXXX facets

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#179]
E.g. http://biocache.ala.org.au/ws/occurrences/search.json?q=new&pageSize=0&flimit=20&facets=el1009

gives:

`errorMessage: "Exception during facet.field: el1009"`

Tomcat log shows:

```
query failed: qt=standard&facet=true&facet.field=el1009&facet.field=el1007&facet.mincount=1&facet.limit=20&facet.sort=count&rows=0&start=0&facet.range.other=before&facet.range.other=after&q=*%3A*&facet.missing=true&sort=score+asc : Exception during facet.field: el1009
2017-11-29 09:37:37,908 [org.ala.biocache.dao.SearchDAOImpl] Error executing query with requestParams: q=*:*&start=0&pageSize=0&sort=score&dir=asc&qc=&facets=el1009&facets=el1007&flimit=20&formattedQuery=*:*&facet=true EXCEPTION: Exception during facet.field: el1009
org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: Exception during facet.field: el1009
	at org.apache.solr.client.solrj.impl.HttpSolrServer.executeMethod(HttpSolrServer.java:552)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:210)
	at org.apache.solr.client.solrj.impl.HttpSolrServer.request(HttpSolrServer.java:206)
	at org.apache.solr.client.solrj.impl.ConcurrentUpdateSolrServer.request(ConcurrentUpdateSolrServer.java:296)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:91)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:310)
	at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:3681)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2509)
	at au.org.ala.biocache.dao.SearchDAOImpl.findByFulltextSpatialQuery(SearchDAOImpl.java:702)
	at au.org.ala.biocache.dao.SearchDAOImpl.findByFulltextSpatialQuery(SearchDAOImpl.java:680)
```

Looks like it might be related to this issue:

https://issues.apache.org/jira/browse/SOLR-7495

**Comment by adam-collins** [comment]
schema.xml differed for el* between indexing server and solr servers. Updates to solr during the week would break the el* indexes causing this failure.

A new index is deployed with same schema. So far it works.
