### ISSUE TITLE
NullPointerException in WMSController.makePointsFromPivot

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#190]
The following stacktrace is in the logs on solr-b4:

```
java.lang.NullPointerException
	at au.org.ala.biocache.web.WMSController.makePointsFromPivot(WMSController.java:2372)
	at au.org.ala.biocache.web.WMSController.queryTile(WMSController.java:2317)
	at au.org.ala.biocache.web.WMSController.getWMSCacheObject(WMSController.java:2146)
	at au.org.ala.biocache.web.WMSController.generateWmsTile(WMSController.java:1489)
...
```

**Comment by ansell** [comment]
Added an explicit NPE in makePointsFromPivot, but not sure what the core behaviour in queryTile should be for null values
