### ISSUE TITLE
org.apache.lucene.search.BooleanQuery: method <init>()V not found

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#197]
A call like this (https://biocache-clustered.ala.org.au/ws/autocomplete/search?q=eucalyptus%20gunnii)  produces the error below:

```
[3:03 PM] Peter Ansell: 2018-04-04 15:02:32,529 [ala.org.au].[/ws].[mainDispatcher]] Servlet.service() for servlet [mainDispatcher] in context with path [/ws] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.lucene.search.BooleanQuery: method <init>()V not found] with root cause
java.lang.NoSuchMethodError: org.apache.lucene.search.BooleanQuery: method <init>()V not found
  at au.org.ala.names.search.ALANameSearcher.autocomplete(ALANameSearcher.java:2101)
[3:04 PM] Peter Ansell: at au.org.ala.biocache.service.SpeciesLookupIndexService.search(SpeciesLookupIndexService.java:242)
  at au.org.ala.biocache.web.AutocompleteController.search(AutocompleteController.java:48)
```

Additional info from Peter Ansell:

> ala-name-matching-3.2-SNAPSHOT.jar and lucene-core-6.4.2.jar are the versions deployed now, with the date that deployment occurred possibly being March 16

**Comment by javier-molina** [comment]
Addressed by https://github.com/AtlasOfLivingAustralia/ala-name-matching/commit/e59bcb4814bffb8034d81c0a258d10025a0aee15

**Comment by djtfmartin** [comment]
this is fixed
