### ISSUE TITLE
NullPointerException during download in SearchDAOImpl

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#199]
The following is a stacktrace generated in the log files when attempting to download using biocache-clustered.

The URL the download was triggered from was:

``https://biocache-clustered.ala.org.au/download?searchParams=%3Fq%3D*%253A*%26fq%3Dmultimedia%253A%2522Sound%2522&targetUri=/occurrences/search&totalRecords=3983``

```
2018-04-06 14:56:24,005 [org.ala.biocache.service.DownloadService] Error in offline download, sending email. download path: /data/biocache-download/biocache-download/ad425ee9-ad26-309f-80ec-bf0a27da52de/1522990583838/records-2018-04-06.zip
java.lang.NullPointerException
	at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy31.writeResultsFromIndexToStream(Unknown Source)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:536)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1188)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1159)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by javier-molina** [comment]
I will close that cob today if I don't hear any further comments.

 #204 and #208 addressed several issues that prevented an end to end download test from succeeding.

**Comment by ansell** [comment]
Not sure what to comment on to keep this from being closed prematurely based on your comment. 

Did you make a change to DownloadService or the AOP chain that could prevent SearchDAOImpl.writeResultsFromIndexToStream from getting a null pointer, and did you write a guard for the line where the null pointer was accessed as shown in the stacktrace?

**Comment by ansell** [comment]
The debug message on the following line would be more useful if it included ``uidStats.keySet()`` in its message.

The null and empty checks on the following line should be separated so that the stack traces and error messages are useful in identifying the cause:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/2.x/src/main/java/au/org/ala/biocache/service/DownloadService.java#L785

**Comment by javier-molina** [comment]
The comment was more about asking on whether this is still an issue.

I could not run a download around this ticket was opened, now I can.

As to the guards I don't think we can possibly review the whole code and fix all posible errors in the given time but rather get it to the level of functionality that current production has.

In summary let me know if you are still seeing this issue and if so the steps to reproduce will be very handy.

**Comment by ansell** [comment]
I will make the changes I included in the comment above and commit them.

**Comment by djtfmartin** [comment]
@ansell can this be closed ?

**Comment by ansell** [comment]
Yes, I fixed the issue
