### ISSUE TITLE
StackOverflowError for databind

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#200]
A databind operation generated a ``StackOverflowError`` in bws-b5-a with the attached stacktrace:

[stackoverflowerror.txt](https://github.com/AtlasOfLivingAustralia/biocache-service/files/1882816/stackoverflowerror.txt)

**Comment by ansell** [comment]
A possibly related exception that appeared today is a ``ConcurrentModificationException``. Not opening a separate issue for it just yet, as it appeared just after the same ``StackOverflowError`` as above and may have been caused partly by it:

```
2018-04-09 03:09:47,566 [org.ala.biocache.service.RestartDataService] failed to save to disk: /tmp/au.org.ala.biocache.util.CollectionsCache.dataResources
com.fasterxml.jackson.databind.JsonMappingException: (was java.util.ConcurrentModificationException) (through reference chain: java.util.LinkedHashMap["null"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:721)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3147)
	at au.org.ala.biocache.service.RestartDataService.saveToDisk(RestartDataService.java:158)
	at au.org.ala.biocache.service.RestartDataService.access$200(RestartDataService.java:38)
	at au.org.ala.biocache.service.RestartDataService$1.run(RestartDataService.java:93)
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:696)
	... 9 more
```

**Comment by javier-molina** [comment]
@ansell do we have any steps to reproduce or is it something that you catched while going through the log?

**Comment by ansell** [comment]
Just recording log entries as issues so they don't disappear into the ether.

``ConcurrentModificationException`` usually indicates that the ``Map`` isn't ``synchronized``, as ``LinkedHashMap`` needs to be if it is accessed on different threads. 

However, I am not sure how that error relates to the Solr ``NamedList`` with cascading ``immutableCopy`` entries. It could be possible to pick up the error and avoid serialising it, as the first entry in the serisalisation chain is ``java.util.HashMap["error"]`` according to the stackoverflowerror.txt file and that should indicate that the result doesn't need to be cached.

**Comment by ansell** [comment]
``RestartDataService`` is also fairly new, so could do with some work. In particular, it doesn't use the APIs directly, but hacks into each of its targets using reflection, so there is no expectation that synchronization will work, or that ConcurentModificationException will not occur. It isn't even possible to safely take a copy of the set defensively because of the lack of synchronization. 

At best, ``RestartDataService`` should protect itself against any errors at all escaping from ``saveToDisk``, and if an error occurs, wipe whatever was written to the file up until that point so corrupted data isn't persisted. Ie, it isn't possible to safely implement ``RestartDataService`` in its current iteration. A safe implementation would need APIs on each of the services that could then be synchronised.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
