### ISSUE TITLE
biocache-2.x: Intermittent thread deadlock during initialisation.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#211]
A few occassions while starting Biocache 2.x locally the following two threads enter a deadlock.
```
"biocache-occurrencecontroller-initialisation@7940" daemon prio=10 tid=0x59 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks Thread-22@7757
	 waiting for Thread-22@7757 to release lock on <0x24df> (a au.org.ala.biocache.dao.SearchDAOImpl)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getServer(SearchDAOImpl.java:335)
	  at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:3744)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getIndexFieldDetails(SearchDAOImpl.java:3092)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getIndexedFields(SearchDAOImpl.java:3156)
	  - locked <0x24de> (a java.lang.Object)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getIndexedFields(SearchDAOImpl.java:3143)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	  at com.sun.proxy.$Proxy30.getIndexedFields(Unknown Source:-1)
	  at au.org.ala.biocache.web.OccurrenceController$1.run(OccurrenceController.java:168)


"Thread-22@7757" daemon prio=5 tid=0x55 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks biocache-occurrencecontroller-initialisation@7940
	 blocks Thread-14@5366
	 waiting for biocache-occurrencecontroller-initialisation@7940 to release lock on <0x24de> (a java.lang.Object)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getIndexedFields(SearchDAOImpl.java:3154)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getIndexedFields(SearchDAOImpl.java:3143)
	  at au.org.ala.biocache.dao.SearchDAOImpl.initServer(SearchDAOImpl.java:372)
	  - locked <0x24df> (a au.org.ala.biocache.dao.SearchDAOImpl)
	  at au.org.ala.biocache.dao.SearchDAOImpl.access$000(SearchDAOImpl.java:99)
	  at au.org.ala.biocache.dao.SearchDAOImpl$2.run(SearchDAOImpl.java:395)

```

This prevents the system from working as for example search requests will ar well be blocked

```
"Thread-14@5366" daemon prio=5 tid=0x3f nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Thread-22@7757 to release lock on <0x24df> (a au.org.ala.biocache.dao.SearchDAOImpl)
	  at au.org.ala.biocache.dao.SearchDAOImpl.getServer(SearchDAOImpl.java:335)
	  at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:3744)
	  at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2551)
	  at au.org.ala.biocache.dao.SearchDAOImpl.searchGroupedFacets(SearchDAOImpl.java:3902)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	  at com.sun.proxy.$Proxy30.searchGroupedFacets(Unknown Source:-1)
	  at au.org.ala.biocache.service.SpeciesImageService$CacheThread.run(SpeciesImageService.java:73)

```

**Comment by javier-molina** [comment]
@djtfmartin, @adam-collins 

See the above for details on the threadlock.

I understand the rational is that biocache-service was colocated in the same tomcat instance as solr and hence we had to manually check/wait until solr was available.

Now with the solr cluster I don't think this is any longer an issue and I would say that solr cluster is simply one of the requirements for biocache-service.

Given the above it should be safer to get rid of those initialising threads and synchronized code and instead put that code in standard Spring DI and @PostConstruct methods for the 2.x branch.

Please let me know if my assumptions are incorrect,  I will basically de-multithreading these:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/4a9e431b4dd8bed575b8ee9e4c86ea00ebf53778/src/main/java/au/org/ala/biocache/web/OccurrenceController.java#L161
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/4a9e431b4dd8bed575b8ee9e4c86ea00ebf53778/src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java#L334


@nickdos fyi

**Comment by djtfmartin** [comment]
@javier-molina i think this sounds sensible.

We do still co-locate SOLR with biocache-service (im thinking of the demo installations), but now we run SOLR as a separate service, so this shouldnt be an issue.

My preference would be just to remove the code completely and reduce complexity (in an already complex set of java classes).

**Comment by ansell** [comment]
APPD and Sandbox will need to take this into account when it comes to migrating them to biocache-service-2.x

**Comment by djtfmartin** [comment]
@javier-molina can this be closed ?
