### ISSUE TITLE
Deadlock: Cassandra3PersistentManager consumer thread  will wait indefinitely.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#212]
The following thread won't stop
```
"Thread-33@10095" prio=5 tid=0x73 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	  at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	  at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anon$1.run(Cassandra3PersistenceManager.scala:1141)

```

Steps to reproduce
1. Search for records and download the dwc fields

Looks like the producer thread never sets the finished flag.
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/096366ba979ba4d1c747448326276803fb2a4333/src/main/scala/au/org/ala/biocache/persistence/Cassandra3PersistenceManager.scala#L1164

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
