### ISSUE TITLE
ClassNotFoundException for Zookeeper client library

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#228]
The following exception is in the log files on bws-b5-a at startup today, indicating a possible issue with the classpath for the Zookeeper client library bundled with biocache-service:

```
2018-06-04 09:07:27,628 [biocache-clustered.ala.org.au-startStop-1-SendThread(ip-172-30-1-24.ap-southeast-2.compute.internal:2181)] WARN org.apache.zookeeper.server.ZooKeeperThread  (ZooKeeperThread.java:60) - Exception occurred from thread biocache-clustered.ala.org.au-startStop-1-SendThread(ip-172-30-1-24.ap-southeast-2.compute.internal:2181)
java.lang.NoClassDefFoundError: org/apache/zookeeper/server/ZooTrace
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1188)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.ZooTrace
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1858)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)
	... 1 more
```

**Comment by ansell** [comment]
This may also be a false positive related to the way Tomcat shuts itself down by killing threads. Closing this issue but can reopen if it occurs again without the following in ``catalina.out`` in addition to the message above that was in ``biocache-service.log``:

```
Jun 04, 2018 9:07:27 AM org.apache.catalina.loader.WebappClassLoaderBase loadClass
INFO: Illegal access: this web application instance has been stopped already.  Could not load org.apache.zookeeper.server.ZooTrace.  The eventual following stack trace is caused by an error thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access, and has no functional impact.
java.lang.IllegalStateException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1743)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1188)
```
