### ISSUE TITLE
Timeout for https://biocache-clustered.ala.org.au/ws/ogc/wms/reflect?

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#232]
This is timing out https://biocache-clustered.ala.org.au/ws/ogc/wms/reflect?
While this produces https://biocache.ala.org.au/ws/ogc/wms/reflect? an image

The relevant log output is:

```
2018-06-15 12:33:16,566 [http-bio-8080-exec-3] INFO au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2156) - search query: *:*
2018-06-15 12:33:16,567 [http-bio-8080-exec-3] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2516) - Solr query: qt=standard&q=*:*&rows=0&facet=true&facet.field=lat_long&facet.mincount=1&facet.limit=-1&facet.missing=true&start=0
2018-06-15 12:33:16,567 [http-bio-8080-exec-3] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:3701) - SOLR query:qt=standard&q=*:*&rows=0&facet=true&facet.field=lat_long&facet.mincount=1&facet.limit=-1&facet.missing=true&start=0





2018-06-15 12:34:36,651 [http-bio-8080-exec-3] ERROR org.apache.solr.client.solrj.impl.CloudSolrClient  (CloudSolrClient.java:1167) - Request to collection biocache failed due to (0) java.net.SocketTimeoutException: Read timed out, retry? 0

==> catalina.out <==
org.apache.solr.client.solrj.SolrServerException: No live SolrServers available to handle this request:[http://aws-sc5b.ala:8983/solr/biocache]
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:426)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1383)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:974)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:990)
	at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:3704)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2518)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2486)
	at au.org.ala.biocache.dao.SearchDAOImpl.getFacetPointsShort(SearchDAOImpl.java:2167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy47.getFacetPointsShort(Unknown Source)
	at au.org.ala.biocache.web.WMSController.queryTile(WMSController.java:2396)
	at au.org.ala.biocache.web.WMSController.getWMSCacheObject(WMSController.java:2176)
	at au.org.ala.biocache.web.WMSController.generateWmsTile(WMSController.java:1497)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: Timeout occured while waiting response from server at: http://aws-sc5b.ala:8983/solr/biocache
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:623)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388)
	... 70 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.client.cache.CachingExec.callBackend(CachingExec.java:592)
	at org.apache.http.impl.client.cache.CachingExec.execute(CachingExec.java:269)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:515)
	... 74 more

```

**Comment by javier-molina** [comment]
Timeout was due to performance tests.

It is still yet to be investigated why it produces an empty image while current prod generates a red spot.

Testing with more parameters would be useful

**Comment by javier-molina** [comment]
A few requests to try when the cluster is not going under any config changes


```
172.30.0.72 - - [18/Jun/2018:09:14:48 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1523913045504&SRS=EPSG%3A3857&ENV=colormode%253Agrid%253Bname%253Acircle%253Bsize%253A3%253Bopacity%253A1&BBOX=15401450.041093,-4227884.5679211,15401755.789206,-4227578.819808&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 346 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:48 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15395029.330718,-4238891.4999927,15397475.315623,-4236445.5150879&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 340 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:49 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15394417.834492,-4237057.0113141,15395029.330718,-4236445.5150879&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 340 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:49 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15399921.300527,-4227884.5679211,15401144.29298,-4226661.5754688&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 340 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:49 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1523913045504&SRS=EPSG%3A3857&ENV=colormode%253Agrid%253Bname%253Acircle%253Bsize%253A3%253Bopacity%253A1&BBOX=15400532.796754,-4227273.0716949,15400838.544867,-4226967.3235818&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 346 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:49 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15393806.338265,-4236445.5150879,15394417.834492,-4235834.0188617&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 300 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:50 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514884543670&SRS=EPSG%3A3857&ENV=color%253A0%253Bname%253Acircle%253Bsize%253A3%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15400532.796754,-4227884.5679211,15400838.544867,-4227578.819808&WIDTH=256&HEIGHT=256 HTTP/1.1" 200 193 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:50 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15395029.330718,-4237057.0113141,15395640.826944,-4236445.5150879&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 300 "-" "-" "13.210.252.120"
172.30.0.72 - - [18/Jun/2018:09:14:50 +1000] "GET /ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15393194.842039,-4238280.0037665,15393806.338265,-4237668.5075403&WIDTH=256&HEIGHT=256 HTTP/1.1" 500 300 "-" "-" "13.210.252.120"
```

**Comment by javier-molina** [comment]
Ok no more timeouts for this call (performance tests related) and this below is a meaningful call that should be used during the tests.

https://biocache-clustered.ala.org.au/ws/webportal/wms/reflect?service=WMS&version=1.1.0&request=GetMap&styles=&format=image/png&layers=ALA:occurrences&transparent=true&CACHE=on&CQL_FILTER=qid:1514883477341&SRS=EPSG%3A3857&ENV=color%253Aff0000%253Bname%253Acircle%253Bsize%253A4%253Buncertainty%253A1%253Bopacity%253A1&BBOX=15393194.842039,-4238280.0037665,15393806.338265,-4237668.5075403&WIDTH=256&HEIGHT=256

**Comment by djtfmartin** [comment]
ok - can we close this issue ?
