### ISSUE TITLE
occurrence online download produces an empty file

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#233]
Thhe call below produces a zip file with empty files
https://biocache-clustered.ala.org.au/ws/occurrences/index/download?q=Macropus+agilis&reasonTypeId=10&fileType=shp

while the same call in prod produces a bunch of non-empty files

The log in the cluster contains this below.

```

2018-06-15 13:02:13,567 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.util.QueryFormatUtils  (QueryFormatUtils.java:486) - pre-processing lsid:urn:lsid:biodiversity.org.au:afd.taxon:2c38441d-6b67-42f9-97c4-85b789c18ba1
2018-06-15 13:02:13,568 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.util.QueryFormatUtils  (QueryFormatUtils.java:499) - lsid = urn:lsid:biodiversity.org.au:afd.taxon:2c38441d-6b67-42f9-97c4-85b789c18ba1
2018-06-15 13:02:13,627 [http-bio-8080-exec-7] WARN org.springframework.web.client.RestTemplate  (RestTemplate.java:559) - GET request for "http://ala-dylan.it.csiro.au/sampling-service/intersect/1/1" resulted in 404 (Not Found); invoking error handler
2018-06-15 13:02:13,628 [http-bio-8080-exec-7] ERROR au.org.ala.biocache.service.AlaLayersService  (AlaLayersService.java:163) - RestTemplate error for http://ala-dylan.it.csiro.au/sampling-service: 404 Not Found
org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:482)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:241)
	at au.org.ala.biocache.service.AlaLayersService.findAnalysisLayerName(AlaLayersService.java:156)
	at au.org.ala.biocache.util.DownloadFields.getIndexFields(DownloadFields.java:160)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1002)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy47.writeResultsFromIndexToStream(Unknown Source)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:539)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:761)
	at au.org.ala.biocache.web.OccurrenceController.occurrenceIndexDownload(OccurrenceController.java:1172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2018-06-15 13:02:13,629 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:1019) - Fields included in download: []
2018-06-15 13:02:13,629 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:1020) - Fields excluded from download: []
2018-06-15 13:02:13,629 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:1021) - The headers in downloads: []
2018-06-15 13:02:13,630 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:1022) - Analysis headers: []
2018-06-15 13:02:13,630 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:1023) - Analysis fields: []
2018-06-15 13:02:13,630 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2516) - Solr query: fl=assertions,institution_uid,collection_uid,data_resource_uid,data_provider_uid&q=lft:[104121+TO+104127]&facet.mincount=1&facet.limit=-1&facet.field=month&facet.field=assertions&facet=true&f.assertions.facet.sort=index&facet.missing=true&rows=0&start=0&sort=score+asc
2018-06-15 13:02:13,630 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:3701) - SOLR query:fl=assertions,institution_uid,collection_uid,data_resource_uid,data_provider_uid&q=lft:[104121+TO+104127]&facet.mincount=1&facet.limit=-1&facet.field=month&facet.field=assertions&facet=true&f.assertions.facet.sort=index&facet.missing=true&rows=0&start=0&sort=score+asc
2018-06-15 13:02:13,688 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2520) - qtime:52
2018-06-15 13:02:13,689 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:2524) - Matched records: 17567
2018-06-15 13:02:13,689 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.writer.ShapeFileRecordWriter  (ShapeFileRecordWriter.java:157) - FEATURES IN HEADER::: assmdPrsnt|crdntPrcsn|cntryCrdnt|cntryInfrr|dcmlLtLngC|frstOfCntr|frstOfMnth|frstOfYr|gdtcDtmAss|incmpltCll|invldCllct|occCltvtdE|prcsnRngMs|sttCrdntMs|uncrtntyRn|unknwnKngd|unrcgnzdGd|zrCrdnts|zrLttd|zrLngtd
2018-06-15 13:02:13,690 [http-bio-8080-exec-7] DEBUG au.org.ala.biocache.writer.ShapeFileRecordWriter  (ShapeFileRecordWriter.java:158) - LOCATION INFO:::21 20 [GeometryDescriptorImpl the_geom <the_geom:Point> nillable 0:1, AttributeDescriptorImpl assmdPrsnt <assmdPrsnt:String> nillable 0:1, AttributeDescriptorImpl crdntPrcsn <crdntPrcsn:String> nillable 0:1, AttributeDescriptorImpl cntryCrdnt <cntryCrdnt:String> nillable 0:1, AttributeDescriptorImpl cntryInfrr <cntryInfrr:String> nillable 0:1, AttributeDescriptorImpl dcmlLtLngC <dcmlLtLngC:String> nillable 0:1, AttributeDescriptorImpl frstOfCntr <frstOfCntr:String> nillable 0:1, AttributeDescriptorImpl frstOfMnth <frstOfMnth:String> nillable 0:1, AttributeDescriptorImpl frstOfYr <frstOfYr:String> nillable 0:1, AttributeDescriptorImpl gdtcDtmAss <gdtcDtmAss:String> nillable 0:1, AttributeDescriptorImpl incmpltCll <incmpltCll:String> nillable 0:1, AttributeDescriptorImpl invldCllct <invldCllct:String> nillable 0:1, AttributeDescriptorImpl occCltvtdE <occCltvtdE:String> nillable 0:1, AttributeDescriptorImpl prcsnRngMs <prcsnRngMs:String> nillable 0:1, AttributeDescriptorImpl sttCrdntMs <sttCrdntMs:String> nillable 0:1, AttributeDescriptorImpl uncrtntyRn <uncrtntyRn:String> nillable 0:1, AttributeDescriptorImpl unknwnKngd <unknwnKngd:String> nillable 0:1, AttributeDescriptorImpl unrcgnzdGd <unrcgnzdGd:String> nillable 0:1, AttributeDescriptorImpl zrCrdnts <zrCrdnts:String> nillable 0:1, AttributeDescriptorImpl zrLttd <zrLttd:String> nillable 0:1, AttributeDescriptorImpl zrLngtd <zrLngtd:String> nillable 0:1]
2018-06-15 13:02:13,690 [http-bio-8080-exec-7] ERROR au.org.ala.biocache.writer.ShapeFileRecordWriter  (ShapeFileRecordWriter.java:168) - The invalid header...assumedPresentOccurrenceStatus|coordinatePrecisionMismatch|countryCoordinateMismatch|countryInferredByCoordinates|decimalLatLongConverted|firstOfCentury|firstOfMonth|firstOfYear|geodeticDatumAssumedWgs84|incompleteCollectionDate|invalidCollectionDate|occCultivatedEscapee|precisionRangeMismatch|stateCoordinateMismatch|uncertaintyRangeMismatch|unknownKingdom|unrecognizedGeodeticDatum|zeroCoordinates|zeroLatitude|zeroLongitude
2018-06-15 13:02:13,691 [http-bio-8080-exec-7] ERROR au.org.ala.biocache.web.OccurrenceController  (OccurrenceController.java:1174) - A Shape File Export needs to include latitude and longitude in the headers: assumedPresentOccurrenceStatus|coordinatePrecisionMismatch|countryCoordinateMismatch|countryInferredByCoordinates|decimalLatLongConverted|firstOfCentury|firstOfMonth|firstOfYear|geodeticDatumAssumedWgs84|incompleteCollectionDate|invalidCollectionDate|occCultivatedEscapee|precisionRangeMismatch|stateCoordinateMismatch|uncertaintyRangeMismatch|unknownKingdom|unrecognizedGeodeticDatum|zeroCoordinates|zeroLatitude|zeroLongitude
java.lang.IllegalArgumentException: A Shape File Export needs to include latitude and longitude in the headers: assumedPresentOccurrenceStatus|coordinatePrecisionMismatch|countryCoordinateMismatch|countryInferredByCoordinates|decimalLatLongConverted|firstOfCentury|firstOfMonth|firstOfYear|geodeticDatumAssumedWgs84|incompleteCollectionDate|invalidCollectionDate|occCultivatedEscapee|precisionRangeMismatch|stateCoordinateMismatch|uncertaintyRangeMismatch|unknownKingdom|unrecognizedGeodeticDatum|zeroCoordinates|zeroLatitude|zeroLongitude
	at au.org.ala.biocache.writer.ShapeFileRecordWriter.initialise(ShapeFileRecordWriter.java:169)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy47.writeResultsFromIndexToStream(Unknown Source)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:539)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:761)
	at au.org.ala.biocache.web.OccurrenceController.occurrenceIndexDownload(OccurrenceController.java:1172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by djtfmartin** [comment]
this is working for me. wondering if it was related to the cluster being in a bad state. QGIS screenshot below

<img width="1439" alt="screenshot 2018-06-18 13 44 02" src="https://user-images.githubusercontent.com/444897/41536502-b244beea-72fd-11e8-9268-9243b05ed53c.png">

**Comment by javier-molina** [comment]
Indeed it is working to me as well, I will close if now.
