### ISSUE TITLE
Cluster: NPE when downloading sensitive records

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/biocache-service#245]
A download of dwc or custom fields for https://biocache-clustered.ala.org.au//occurrence/search?q=sensitive%3A* produces a NPE with the stack trace at the bottom.

You need to have one of the SDS roles to source the sensitive records.

```
2018-06-28 16:02:51,944 [biocachedownload-pool-50000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:1268) - Error in offline download, sending email. download path: /data/biocache-download/biocache-download/b8440880-a800-3e0a-b710-a8aecca1da90/1530165771896/records-2018-06-28-npe-1.zip
java.lang.NullPointerException
        at au.org.ala.biocache.util.DownloadFields.getIndexFields(DownloadFields.java:156)
        at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1094)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
        at com.sun.proxy.$Proxy44.writeResultsFromIndexToStream(Unknown Source)
        at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:539)
        at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1187)
        at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1158)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by djtfmartin** [comment]
fixed.
