### ISSUE TITLE
Regression: NullPointerException in SpeciesImageService CacheThread run

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#324]
A NullPointerException is reported in the log files when running the SpeciesImageService CacheThread:

```
2018-09-13 14:52:44,164 [Thread-11] ERROR au.org.ala.biocache.service.SpeciesImageService  (SpeciesImageService.java:117) - 
java.lang.NullPointerException
	at au.org.ala.biocache.util.QueryFormatUtils.formatTitleMap(QueryFormatUtils.java:707)
	at au.org.ala.biocache.util.QueryFormatUtils.formatQueryTerm(QueryFormatUtils.java:737)
	at au.org.ala.biocache.util.QueryFormatUtils.formatSearchQuery(QueryFormatUtils.java:125)
	at au.org.ala.biocache.util.QueryFormatUtils.formatSearchQuery(QueryFormatUtils.java:106)
	at au.org.ala.biocache.dao.SearchDAOImpl.searchGroupedFacets(SearchDAOImpl.java:4003)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy44.searchGroupedFacets(Unknown Source)
	at au.org.ala.biocache.service.SpeciesImageService$CacheThread.run(SpeciesImageService.java:72)
```

**Comment by djtfmartin** [comment]
Im finding this one difficult to action without a URL.
I think its this line:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/7ff68304a4abe712761c7b890a119860dd756820/src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java#L707

Ill add a null guard on the equivalent line in master. Please reopen if we find a URL to recreate.
