### ISSUE TITLE
Temporary files for Shapefile downloads are being written to /tmp/tomcat7-tomcat7-tmp

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#330]
The large temporary files for Shapefile downloads are being written to ``/tmp/tomcat7-tomcat7-tmp``, which uses the root file system on the standard ALA layout and when full causes other issues. They should be written to a directory under ``/data/`` to avoid filling up the root file system.

The files in that directory when the root filesystem filled up today were:

```
/tmp/tomcat7-tomcat7-tmp# du -hs *
7.9M    records-2018-09-251107063236509048079.fix
19M    records-2018-09-251515248714604408838.shp
5.3M    records-2018-09-25353093210698407006.shx
9.0G    records-2018-09-255408108513963935020.dbf
```

**Comment by ansell** [comment]
This issue happened again today (note the incomplete log message at the end because the partition was full at that point). The log messages seem to indicate that one copy of the shapefiles are in ``data/biocache-download/tmp/...``, but there is a bug at some other point where the files are landing in ``/tmp/tomcat7-tomcat7-tmp``:

```
2018-10-05 15:00:52,992 [Thread-34917] ERROR org.geotools.data.shapefile  (ShpFiles.java:247) - The following locker still has a lock: read on file:/data/biocache-download/tmp/1538712178903/records-2018-10-05/records-2018-10-05.shp by org.geotools.data.shapefile.shp.ShapefileReader
2018-10-05 15:00:52,992 [Thread-34917] ERROR org.geotools.data.shapefile  (ShpFiles.java:247) - The following locker still has a lock: read on file:/data/biocache-download/tmp/1538712178903/records-2018-10-05/records-2018-10-05.dbf by org.geotools.data.shapefile.dbf.DbaseFileReader
2018-10-05 15:00:52,992 [Thread-34917] ERROR org.geotools.data.shapefile  (ShpFiles.java:247) - The following locker still has a lock: read on file:/data/biocache-download/tmp/1538712178903/records-2018-10-05/records-2018-10-05.fix by org.geotools.data.shapefile.fid.IndexedFidReader
2018-10-05 15:00:52,994 [Thread-34917] INFO au.org.ala.biocache.writer.ShapeFileRecordWriter  (ShapeFileRecordWriter.java:278) - Copying Shape zip file to outputstream
2018-10-05 15:00:52,996 [Thread-34917] ERROR au.org.ala.biocache.writer.ShapeFileRecordWriter  (ShapeFileRecordWriter.java:298) - Unable to create ShapeFile
java.io.IOException: Current fid index is null, next must be called before write()
	at org.geotools.data.shapefile.fid.IndexedFidWriter.write(IndexedFidWriter.java:253)
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:95)
	at org.geotools.data.shapefile.ShapefileFeatureWriter.close(ShapefileFeatureWriter.java:220)
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.close(IndexedShapefileFeatureWriter.java:103)
	at org.geotools.data.InProcessLockingManager$1.close(InProcessLockingManager.java:350)
	at org.geotools.data.store.DiffTransactionState.commit(DiffTransactionState.java:207)
	at org.geotools.data.DefaultTransaction.commit(DefaultTransaction.java:186)
	at au.org.ala.biocache.writer.ShapeFileRecordWriter.finalise(ShapeFileRecordWriter.java:229)
	at au.org.ala.biocache.dao.SearchDAOImpl$3.run(SearchDAOImpl.java:1275)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: No space left on device
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211)
	at org.geotools.data.shapefile.dbf.DbaseFileWriter.write(DbaseFileWriter.java:178)
	at org.geotools.data.shapefile.dbf.DbaseFileWriter.write(DbaseFileWriter.java:221)
	at org.geotools.data.shapefile.ShapefileFeatureWriter.write(ShapefileFeatureWriter.java:398)
	at org.geotools.data.shapefile.IndexedShapefileFeatureWriter.write(IndexedShapefileFeatureWriter.java:96)
	at org.geotools.data.InProcessLockingManager$1.write(InProcessLockingManager.java:337)
	at org.geotools.data.store.DiffTransactionState.commit(DiffTransactionState.java:189)
	... 4 more
2018-10-05 15:00:53,044 [biocachedownload-pool-50000000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.writer.RecordWriterException  (RecordWriterException.java:47) - msg
2018-10-05 15:00:53,045 [biocachedownload-pool-50000000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (Downl
```

**Comment by ansell** [comment]
Fixed by changing where tomcat thinks its temporary directory is. Not sure what the original cause is, but the fix is in ala-install at:

https://github.com/AtlasOfLivingAustralia/ala-install/commit/16dc84f24500cdc3cb0998c9b3671b84bb85d581
