### ISSUE TITLE
Problem in occurrence.year type mapping

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/biocache-service#368]
Trying to upgrade our software to the latest versions of `biocache-service` and `biocache-store` our solr index stopped to work with this exception: 

```
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.Integer field au.org.ala.biocache.dto.OccurrenceIndex.year to java.lang.String.
(...)
Caused by: org.apache.solr.client.solrj.beans.BindingException: Exception while setting value : 1987 on java.lang.Integer au.org.ala.biocache.dto.OccurrenceIndex.year
        at org.apache.solr.client.solrj.beans.DocumentObjectBinder$DocField.set(DocumentObjectBinder.java:455)
        at org.apache.solr.client.solrj.beans.DocumentObjectBinder$DocField.inject(DocumentObjectBinder.java:438)
        at org.apache.solr.client.solrj.beans.DocumentObjectBinder.getBean(DocumentObjectBinder.java:67)
```

Debugging that error I found that https://github.com/AtlasOfLivingAustralia/biocache-service/commit/8e2841f58ddc2941d66f99946cdadfc80450e6f3
was causing this issue because in our index the `year` is of `String` type instead of `Integer`.

Maybe a fix is to change the schema of `year` from `int` to `tint` like `occurrence_decade_i`. Compare:
http://demo.gbif.es:8983/solr/biocache/select?fl=year&indent=on&q=*:*&wt=json
http://demo.gbif.es:8983/solr/biocache/select?fl=occurrence_decade_i&indent=on&q=*:*&wt=json
in our demo.

Somehow this is related with https://github.com/AtlasOfLivingAustralia/biocache-store/issues/310.

**Comment by vjrj** [comment]
I'm closing this because my reindex was not getting the correct year fields values because I missed the 
`rm -rf /data/solr/biocache/conf` step mentioned in https://github.com/AtlasOfLivingAustralia/biocache-store/issues/315.
