### ISSUE TITLE
Illegal character in speciesKvp Cache Refresh Timer call to ListsService

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#372]
The following error is in the logs on `prod-bdown-b5`:

```
==> /var/log/tomcat7/biocache-service.log <==
2019-04-17 16:12:19,035 [speciesKvp Cache Refresh Timer] ERROR au.org.ala.biocache.service.DownloadService  (ListsService.java:188) - failed to get species list kvp for list: longitude"
java.net.URISyntaxException: Illegal character in path at index 54: https://lists.ala.org.au/ws/speciesListItems/longitude"?includeKVP=true
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at au.org.ala.biocache.service.ListsService.getKvp(ListsService.java:162)
	at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.googlecode.ehcache.annotations.resolver.ThreadLocalCacheEntryFactory.createEntry(ThreadLocalCacheEntryFactory.java:36)
	at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.createEntry(RefreshingCacheEntryFactory.java:60)
	at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.updateEntryValue(RefreshingCacheEntryFactory.java:44)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:259)
	at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache.refreshElement(RefreshingSelfPopulatingCache.java:143)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:153)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:106)
	at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache$2.run(RefreshingSelfPopulatingCache.java:100)
	at com.googlecode.ehcache.annotations.support.TimerTaskSchedulerAdapter$1.run(TimerTaskSchedulerAdapter.java:42)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
2019-04-17 16:12:19,060 [speciesKvp Cache Refresh Timer] ERROR au.org.ala.biocache.service.DownloadService  (ListsService.java:188) - failed to get species list kvp for list: longitude;
java.net.URISyntaxException: Illegal character in path at index 55: https://lists.ala.org.au/ws/speciesListItems/longitude;?includeKVP=true
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at au.org.ala.biocache.service.ListsService.getKvp(ListsService.java:162)
	at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at com.googlecode.ehcache.annotations.resolver.ThreadLocalCacheEntryFactory.createEntry(ThreadLocalCacheEntryFactory.java:36)
	at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.createEntry(RefreshingCacheEntryFactory.java:60)
	at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.updateEntryValue(RefreshingCacheEntryFactory.java:44)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:259)
	at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache.refreshElement(RefreshingSelfPopulatingCache.java:143)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:153)
	at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:106)
	at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache$2.run(RefreshingSelfPopulatingCache.java:100)
	at com.googlecode.ehcache.annotations.support.TimerTaskSchedulerAdapter$1.run(TimerTaskSchedulerAdapter.java:42)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

There were at least two queries executing at the time the error occurred but they may not be relevant:

```
==> /var/log/nginx/access.log <==
[REDACTED_USER_1] - - [17/Apr/2019:16:12:40 +1000] "GET /ws/occurrences/index/download?q=taxon_name%3A%22Strophurus%20ciliaris%22&reasonTypeId=7&sourceTypeId=2001&esc=%5C&sep=%09&file=data HTTP/1.1" 200 475451 "-" "ALA4R 1.7.0" "[REDACTED_USER_1]" request_time=70.197 upstream_response_time=70.192 upstream_connect_time=0.000 upstream_header_time=10.856 upstream_cache_status=-
[REDACTED_USER_2]- - [17/Apr/2019:16:12:48 +1000] "GET /ws/occurrences/index/download?q=taxon_name%3A%22Boletus%20prolinius%22&reasonTypeId=4 HTTP/1.1" 200 8367 "-" "R (3.5.1 x86_64-pc-linux-gnu x86_64 linux-gnu)" "[REDACTED_USER_2]" request_time=61.034 upstream_response_time=61.036 upstream_connect_time=0.000 upstream_header_time=60.908 upstream_cache_status=-
```

**Comment by ansell** [comment]
```
2019-04-24 09:52:18,930 [speciesKvp Cache Refresh Timer] ERROR au.org.ala.biocache.service.DownloadService  (ListsService.java:188) - failed to get species list kvp for list: longitude"
java.net.URISyntaxException: Illegal character in path at index 54: https://lists.ala.org.au/ws/speciesListItems/longitude"?includeKVP=true
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at au.org.ala.biocache.service.ListsService.getKvp(ListsService.java:162)
        at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at com.googlecode.ehcache.annotations.resolver.ThreadLocalCacheEntryFactory.createEntry(ThreadLocalCacheEntryFactory.java:36)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.createEntry(RefreshingCacheEntryFactory.java:60)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.updateEntryValue(RefreshingCacheEntryFactory.java:44)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:259)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache.refreshElement(RefreshingSelfPopulatingCache.java:143)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:153)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:106)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache$2.run(RefreshingSelfPopulatingCache.java:100)
        at com.googlecode.ehcache.annotations.support.TimerTaskSchedulerAdapter$1.run(TimerTaskSchedulerAdapter.java:42)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
2019-04-24 09:52:18,954 [speciesKvp Cache Refresh Timer] ERROR au.org.ala.biocache.service.DownloadService  (ListsService.java:188) - failed to get species list kvp for list: longitude;^@
java.net.URISyntaxException: Illegal character in path at index 55: https://lists.ala.org.au/ws/speciesListItems/longitude;^@?includeKVP=true
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at au.org.ala.biocache.service.ListsService.getKvp(ListsService.java:162)
        at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:701)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
        at com.googlecode.ehcache.annotations.resolver.ThreadLocalCacheEntryFactory.createEntry(ThreadLocalCacheEntryFactory.java:36)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.createEntry(RefreshingCacheEntryFactory.java:60)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.updateEntryValue(RefreshingCacheEntryFactory.java:44)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:259)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache.refreshElement(RefreshingSelfPopulatingCache.java:143)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:153)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:106)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache$2.run(RefreshingSelfPopulatingCache.java:100)
        at com.googlecode.ehcache.annotations.support.TimerTaskSchedulerAdapter$1.run(TimerTaskSchedulerAdapter.java:42)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

There were no active download requests active at the time based on the nginx log.

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
