### ISSUE TITLE
Cannot set api.check.url in config file

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#373]
The configuration property `api.check.url` appears to be visible in the same way as other configuration properties:

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/9f08a35b6b3735af5c69eace2d882a4bc367112d/src/main/java/au/org/ala/biocache/web/AbstractSecureController.java#L41

However, attempting to set api.check.url in the config file results in the following stacktrace:

```
2019-04-24 17:39:34,599 [biocache-ws-test.ala.org.au-startStop-1] ERROR org.springframework.web.servlet.DispatcherServlet  (FrameworkServlet.java:470) - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'api' defined in class path resource [au/org/ala/biocache/config/SwaggerConfig.class]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'check.url' of bean class [springfox.documentation.spring.web.plugins.Docket]: Nested property in path 'check.url' does not exist; nested exception is org.springframework.beans.NotReadablePropertyException: Invalid property 'check' of bean class [springfox.documentation.spring.web.plugins.Docket]: Bean property 'check' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1455)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:638)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:651)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:602)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:665)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:521)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:462)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1085)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5318)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5610)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1091)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1980)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'check.url' of bean class [springfox.documentation.spring.web.plugins.Docket]: Nested property in path 'check.url' does not exist; nested exception is org.springframework.beans.NotReadablePropertyException: Invalid property 'check' of bean class [springfox.documentation.spring.web.plugins.Docket]: Bean property 'check' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:897)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:57)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1452)
	... 33 more
Caused by: org.springframework.beans.NotReadablePropertyException: Invalid property 'check' of bean class [springfox.documentation.spring.web.plugins.Docket]: Bean property 'check' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.BeanWrapperImpl.getPropertyValue(BeanWrapperImpl.java:709)
	at org.springframework.beans.BeanWrapperImpl.getNestedBeanWrapper(BeanWrapperImpl.java:555)
	at org.springframework.beans.BeanWrapperImpl.getBeanWrapperForPropertyPath(BeanWrapperImpl.java:532)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:894)
	... 36 more
```

Need to be able to override it so that others are not using auth.ala.org.au as their source of apikeys, and also need to be able to override ALA test systems to use `auth-test.ala.org.au` rather than `auth.ala.org.au`

**Comment by ansell** [comment]
Going to try this one out again as I need to review auth-test.ala.org.au/apikey today

**Comment by ansell** [comment]
Changing the property to `apikey.check.url` seems to have fixed the issue, so there must be something special intercepting or otherwise interfering with `api.*` properties.
