### ISSUE TITLE
Batch taxon search form not working

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#375]
@nickdos commented on [Fri May 10 2019](https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/298)

Reported by Niels (in AVH): https://support.ehelp.edu.au/a/tickets/32370 

https://biocache.ala.org.au/search#tab_taxaUpload

type a couple of names, press search. 

https://biocache-ws.ala.org.au/ws/occurrences/batchSearch

results in 400 error:

![image](https://user-images.githubusercontent.com/532845/57497424-fb103c80-731a-11e9-8c7b-a134dcc4211b.png)

Also affects the catalogue number search (https://biocache.ala.org.au/search#tab_catalogUpload).

This might be related to the AUTH issue seen in SP, when doing a POST(?).

---

@nickdos commented on [Fri May 10 2019](https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/298#issuecomment-491134565)

Looks like an issue in biocache-service, so will move it there.

**Comment by nickdos** [comment]
On test, the only thing I see in `biocache-service.log` is

> 2019-05-10 12:48:35,618 [http-bio-127.0.0.1-8080-exec-10] INFO au.org.ala.biocache.web.OccurrenceController  (OccurrenceController.java:1064) - /occurrences/batchSearch with action=Search

**Comment by ansell** [comment]
The new BIE that @charvolant deployed recently is now returning HTTP 404 when it doesn't recognise taxa. Effectively it is intended to say "taxa doesn't exist". However, some of our other code may need to be updated to work properly with this and handle HTTP 404 specifically. The following is a trace from `prod-bdown-b5` which may be relevant to this. If it isn't relevant I will create a new issue for it.

```
==> /var/log/tomcat7/biocache-service.log <==
2019-05-13 11:15:06,790 [http-bio-127.0.0.1-8080-exec-89] WARN org.springframework.web.client.RestTemplate  (RestTemplate.java:559) - POST request for "https://bie.ala.org.au/ws/species/guids/bulklookup.json" resulted in 404 (null); invoking error handler
2019-05-13 11:15:06,790 [http-bio-127.0.0.1-8080-exec-89] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:163) - Requested URI: https://bie.ala.org.au/ws/species/guids/bulklookup.json
2019-05-13 11:15:06,791 [http-bio-127.0.0.1-8080-exec-89] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:164) - With POST body: guid=Plantago lanceolata|http://id.biodiversity.org.au/node/apni/2899343|English plantain|Plantae|Plantaginaceae&guid=Pseudocheirus peregrinus|urn:lsid:biodiversity.org.au:afd.taxon:003decd6-ec3d-468e-909d-da396a6dd1f6|Common Ringtail Possum|Animalia|Pseudocheiridae
2019-05-13 11:15:06,791 [http-bio-127.0.0.1-8080-exec-89] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:165) - RestTemplate error: 404 null
org.springframework.web.client.HttpClientErrorException: 404 null
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:88)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:566)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:524)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:482)
	at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:327)
	at au.org.ala.biocache.service.SpeciesLookupRestService.getNameDetailsForGuids(SpeciesLookupRestService.java:158)
	at au.org.ala.biocache.service.SpeciesLookupRestService.getSpeciesDetails(SpeciesLookupRestService.java:190)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeTaxonDetailsToStream(SearchDAOImpl.java:868)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeFacetToStream(SearchDAOImpl.java:821)
	at sun.reflect.GeneratedMethodAccessor251.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy44.writeFacetToStream(Unknown Source)
	at au.org.ala.biocache.web.OccurrenceController.downloadFacet(OccurrenceController.java:916)
	at sun.reflect.GeneratedMethodAccessor250.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-05-13 11:15:06,836 [http-bio-127.0.0.1-8080-exec-89] INFO au.org.ala.biocache.dao.JsonPersistentQueueDAOImpl  (JsonPersistentQueueDAOImpl.java:236) - Deleting /data/cache/downloads/offline1557710106520.json false

==> /var/log/nginx/access.log <==
[REDACTED] - - [13/May/2019:11:15:06 +1000] "GET /ws/occurrences/facets/download?facets=names_and_lsid&lookup=true&count=true&lists=true&q=qid:1557710049489&fq=species_list_uid%3A(dr7904%20OR%20dr649%20OR%20dr650%20OR%20dr2285%20OR%20dr651%20OR%20dr652%20OR%20dr653%20OR%20dr654%20OR%20dr655%20OR%20dr2201) HTTP/1.1" 200 996 "https://spatial.ala.org.au/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" "[REDACTED]" request_time=0.318 upstream_response_time=0.316 upstream_connect_time=0.000 upstream_header_time=0.316 upstream_cache_status=-
```

**Comment by nickdos** [comment]
@djtfmartin could you look at this, if you're still working on biocache-service? This is fairly urgent as prod is broken for this function.

**Comment by nickdos** [comment]
@adam-collins said he'll take a look at this.

**Comment by nickdos** [comment]
Fix deployed today :+1:

**Comment by charvolant** [comment]
This has made a reappearance. See https://support.ehelp.edu.au/a/tickets/38959

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
