### ISSUE TITLE
Convert SOLR fields to use docValues

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#383]
Adam has started this on the [`docValues` branch](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/docvalues). See https://lucene.apache.org/solr/guide/6_6/docvalues.html for more info.

Rational is the change to use `docValues` should improve SOLR performance by reducing both memory and IO for downloads in particular.

EDIT: Dave has used docValues in new pipelines work - see his branch https://github.com/AtlasOfLivingAustralia/biocache-service/tree/experimental/pipelines. Plan is to mirror schema changes in master and deploy to prod after thorough functional testing (Gatlin tests).

**Comment by javier-molina** [comment]
There are support tickets like https://support.ehelp.edu.au/a/tickets/35512 that depend on this

> Hi again,
Thanks, some of the ‘Tools’ on the spatial portal of ALA are now working, but others are not. For example, I’ve tried to get a ‘Points to Grid’ analysis for Australia of CLASS: REPTILIA, and this has failed, even trying different grid cell size (e.g. 0.5 degree, 1 degree). This use to be one of the original basic outputs of ALA, so it’s hard to see why its taking so long and failing.

**Comment by ansell** [comment]
The test docValues collection being used by `biocache-ws-test.ala.org.au` is not completely compatible with `biocache-service` at this point. There are queries coming in which are throwing `NullPointerException` inside of Solr due to not including fields in the query:

```
==> /var/log/tomcat7/biocache-service.log <==
2019-07-30 14:48:21,691 [http-bio-127.0.0.1-8080-exec-3] INFO au.org.ala.biocache.dao.SearchDAOImpl  (SearchDAOImpl.java:3736) - search query: text:Pterostylis fischii
2019-07-30 14:48:21,818 [http-bio-127.0.0.1-8080-exec-3] ERROR org.apache.solr.client.solrj.impl.CloudSolrClient  (CloudSolrClient.java:1167) - Request to collection biocache-2019-07-27-00-48 failed due to (500) org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://aws-sc8b.ala:8983/solr/biocache-2019-07-27-00-48: java.lang.NullPointerException
, retry? 0

==> /var/log/tomcat7/catalina.out <==
org.apache.solr.client.solrj.SolrServerException: No live SolrServers available to handle this request:[http://aws-sc4b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc7b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc6b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc2b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc8b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc3b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc1b.ala:8983/solr/biocache-2019-07-27-00-48, http://aws-sc5b.ala:8983/solr/biocache-2019-07-27-00-48]
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:426)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1383)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1134)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1073)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:974)
	at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:990)
	at au.org.ala.biocache.dao.SearchDAOImpl.query(SearchDAOImpl.java:4011)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2724)
	at au.org.ala.biocache.dao.SearchDAOImpl.runSolrQuery(SearchDAOImpl.java:2692)
	at au.org.ala.biocache.dao.SearchDAOImpl.getLegend(SearchDAOImpl.java:3764)
	at au.org.ala.biocache.dao.SearchDAOImpl.getColours(SearchDAOImpl.java:4470)
	at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at com.googlecode.ehcache.annotations.interceptor.EhCacheInterceptor.invokeCacheable(EhCacheInterceptor.java:142)
	at com.googlecode.ehcache.annotations.interceptor.EhCacheInterceptor.invoke(EhCacheInterceptor.java:81)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy54.getColours(Unknown Source)
	at au.org.ala.biocache.web.WMSController.getWMSCacheObject(WMSController.java:2161)
	at au.org.ala.biocache.web.WMSController.generateWmsTile(WMSController.java:1486)
	at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://aws-sc8b.ala:8983/solr/biocache-2019-07-27-00-48: java.lang.NullPointerException

	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:612)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:279)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:268)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:447)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:388)
	... 73 more

==> /var/log/nginx/access.log <==
[REDACTED] - - [30/Jul/2019:14:48:21 +1000] "GET /ws/mapping/wms/reflect?q=text%3APterostylis+fischii&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=true&ENV=colormode%3Abasis_of_record%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1%3B&GRIDDETAIL=32&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=12523442.714243276,-7514065.628545966,15028131.257091932,-5009377.085697311 HTTP/1.1" 500 556 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:68.0) Gecko/20100101 Firefox/68.0" "[REDACTED]" request_time=0.137 upstream_response_time=0.136 upstream_connect_time=0.000 upstream_header_time=0.136 upstream_cache_status=-
```

**Comment by javier-molina** [comment]
https://support.ehelp.edu.au/a/tickets/35512 is being blocked by this.

**Comment by brucehyslop** [comment]
DocValues are now being used as of the Core Infrastructure Upgrade part 1, biocache-service v3
