### ISSUE TITLE
IndexOutOfBoundsException in SpeciesLookupRestService

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#390]
There is a `java.lang.IndexOutOfBoundsException` in the log files for biocache-service tracing back to `SpeciesLookupRestService`. The caller in this case is `aws-spatial-prod`:

```
==> /var/log/tomcat7/biocache-service.log <==
2019-07-29 15:53:50,892 [http-bio-127.0.0.1-8080-exec-9] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:216) - Requested URI: https://bie-ws.ala.org.au/ws/species/guids/bulklookup.json
2019-07-29 15:53:50,893 [http-bio-127.0.0.1-8080-exec-9] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:217) - With POST body: guid=Taxiphyllum taxirameum|http://id.biodiversity.org.au/node/ausmoss/10116932||Plantae|Hypnaceae&guid=Dawsonia polytrichoides|http://id.biodiversity.org.au/node/ausmoss/10069723||Plantae|Polytrichaceae&guid=Dawsonia longiseta|http://id.biodiversity.org.au/node/ausmoss/10069699||Plantae|Polytrichaceae&guid=Ditrichum difficile|http://id.biodiversity.org.au/node/ausmoss/10072295||Plantae|Ditrichaceae&guid=Fossombronia papillata|http://id.biodiversity.org.au/node/apni/2887977||Plantae|Fossombroniaceae&guid=Splachnobryum obtusum|http://id.biodiversity.org.au/node/ausmoss/10114120||Plantae|Pottiaceae&guid=Entodon plicatus|http://id.biodiversity.org.au/node/ausmoss/10075187||Plantae|Entodontaceae&guid=Gemmabryum coronatum|http://id.biodiversity.org.au/node/ausmoss/10128818||Plantae|Bryaceae&guid=Riccardia|http://id.biodiversity.org.au/node/apni/2911854||Plantae|Aneuraceae&guid=Rosulabryum subfasciculatum|http://id.biodiversity.org.au/node/ausmoss/10110713||Plantae|Bryaceae&guid=Fabronia scottiae|http://id.biodiversity.org.au/node/ausmoss/10077861||Plantae|Fabroniaceae&guid=Fissidens beckettii|http://id.biodiversity.org.au/node/ausmoss/10078341||Plantae|Fissidentaceae&guid=Fissidens dietrichiae|http://id.biodiversity.org.au/node/ausmoss/10079675||Plantae|Fissidentaceae&guid=Gemmabryum dichotomum|http://id.biodiversity.org.au/node/ausmoss/10128935||Plantae|Bryaceae&guid=Leucobryum|http://id.biodiversity.org.au/node/ausmoss/10093750||Plantae|Leucobryaceae&guid=Lunularia cruciata|NZOR-6-112215||Plantae|Lunulariaceae&guid=Lunularia cruciata|http://id.biodiversity.org.au/node/apni/2899866||Plantae|Lunulariaceae&guid=Papillaria flexicaulis|http://id.biodiversity.org.au/node/ausmoss/10100654||Plantae|Meteoriaceae
2019-07-29 15:53:50,893 [http-bio-127.0.0.1-8080-exec-9] ERROR au.org.ala.biocache.service.SpeciesLookupRestService  (SpeciesLookupRestService.java:218) - RestTemplate error: Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at au.org.ala.biocache.service.SpeciesLookupRestService.getNameDetailsForGuids(SpeciesLookupRestService.java:209)
	at au.org.ala.biocache.service.SpeciesLookupRestService.getSpeciesDetails(SpeciesLookupRestService.java:243)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeTaxonDetailsToStream(SearchDAOImpl.java:909)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeFacetToStream(SearchDAOImpl.java:862)
	at sun.reflect.GeneratedMethodAccessor317.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198)
	at com.sun.proxy.$Proxy46.writeFacetToStream(Unknown Source)
	at au.org.ala.biocache.web.OccurrenceController.downloadFacet(OccurrenceController.java:892)
	at sun.reflect.GeneratedMethodAccessor316.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at au.org.ala.biocache.web.LoggerConfigFilter.doFilter(LoggerConfigFilter.java:26)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2019-07-29 15:53:50,922 [http-bio-127.0.0.1-8080-exec-9] INFO au.org.ala.biocache.dao.JsonPersistentQueueDAOImpl  (JsonPersistentQueueDAOImpl.java:236) - Deleting /data/cache/downloads/offline1564379630639.json false

==> /var/log/nginx/access.log <==
52.63.206.55 - - [29/Jul/2019:15:53:50 +1000] "GET /ws/occurrences/facets/download?facets=names_and_lsid&lookup=true&count=true&q=qid:1564377977569&fq=species_group%3ABryophytes HTTP/1.1" 200 4202 "-" "Jakarta Commons-HttpClient/3.1" "52.63.206.55" request_time=0.287 upstream_response_time=0.284 upstream_connect_time=0.000 upstream_header_time=0.284 upstream_cache_status=-
52.63.206.55 - - [29/Jul/2019:15:53:50 +1000] "GET /ws/occurrence/facets?facets=names_and_lsid&flimit=0&q=qid:1564377977569&fq=species_group%3AChromista HTTP/1.1" 200 12 "-" "Jakarta Commons-HttpClient/3.1" "52.63.206.55" request_time=0.011 upstream_response_time=0.008 upstream_connect_time=0.000 upstream_header_time=0.008 upstream_cache_status=-
```

**Comment by sadeghim** [comment]
There is another evidence for this. Here is an offline download causing same problem:
```
[
  {
    "downloadParams": "?q=qid%3A1582507139142",
    "downloadType": "RECORDS_INDEX",
    "fileLocation": "/data/biocache-download/biocache-download/319810e3-9792-3933-a9fb-a4fde4c534b8/1582507155362/Batch_17.zip",
    "includeSensitive": false,
    "interrupt": {},
    "ipAddress": "127.0.0.1",
    "lastUpdate": {
      "date": 24,
      "day": 1,
      "hours": 12,
      "minutes": 35,
      "month": 1,
      "seconds": 16,
      "time": 1582508116051,
      "timezoneOffset": -660,
      "year": 120
    },
    "processingThreadName": "biocache-download-control-largeSolr-50000000-RECORDS_INDEX-poolsize-1",
    "recordsDownloaded": 418000,
    "requestParams": {
      "customHeader": "",
      "dir": "asc",
      "displayString": "(raw_name:\"Chlamydera cerviniventris\" OR raw_name:\"Grallina cyanoleuca\")",
      "doiDisplayUrl": "https://biocache.ala.org.au/download/doi?doi=",
      "dwcHeaders": true,
      "encodedParams": "q=qid%3A1582507139142&start=0&pageSize=0&sort=score&dir=asc&qc=&fl=occurrence_date%2Ccountry%2Cgeospatial_kosher%2Cyear%2Cpoint-0.01%2Cdata_resource%2Ctaxonomic_kosher%2Clat_long%2Crecord_number%2Cspecies_guid%2Cstate_conservation%2Coccurrence_year%2Cgenus_guid%2Ctaxon_concept_lsid%2Coccurrence_remarks%2Cpoint-0.1%2Crank%2Cdata_provider%2Cuser_assertions%2Cid%2Cstate%2Cassertions%2Ccommon_name%2Craw_common_name%2Corder%2Clongitude%2Cbasis_of_record%2Ccollection_uid%2Cimage_url%2Clocation_remarks%2Cpoint-1%2Csensitive%2Cpoint-0.0001%2Cidentification_verification_status%2Ccountry_code%2Clicense%2Ccollectors%2Cmonth%2Cgenus%2Coccurrence_id%2Cibra%2Clft%2Cspecies_group%2Csubspecies%2Coccurrence_details%2Ccollection_name%2Ccollection_code%2Crank_id%2Craw_taxon_name%2Coccurrence_date_end_dt%2Cdata_resource_uid%2Cdata_hub%2Clatitude%2Cdata_provider_uid%2Ctype_status%2Cinstitution_name%2Ccollector%2Cimcra%2Cinstitution_uid%2Csubspecies_guid%2Crights%2Ctaxon_name%2Cclass%2Crgt%2Cgrid_ref%2Ccatalogue_number%2Caust_conservation%2Cdata_hub_uid%2Cnames_and_lsid%2Cpoint-0.001%2Cphotographer_s%2Ccoordinate_uncertainty%2Call_image_url%2Ckingdom%2Cinstitution_code%2Craw_type_status%2Cplaces%2Cmultimedia%2Cphylum%2Cspecies%2Craw_basis_of_record%2Cfamily&formattedQuery=(raw_name%3A%22Chlamydera%20cerviniventris%22%20OR%20raw_name%3A%22Grallina%20cyanoleuca%22)&facet=false&email=XXXX&reason=&file=Batch_17&fields=rowkey%2Clanguage%2Clicense%2Crightsholder%2Caccess_rights%2Cbibliographic_citation%2Cinstitution_id%2Ccollection_id%2Cdataset_id%2Cinstitution_code%2Ccollection_code%2Cdataset_name%2Cowner_institution_code%2Cbasis_of_record%2Cdynamic_properties%2Cprovenance%2Crights%2Csource%2Coccurrence_id%2Ccatalogue_number%2Crecord_number%2Ccollector%2Cindividual_count%2Corganism_quantity%2Corganism_quantity_type%2Craw_sex%2Clife_stage%2Creproductive_condition%2Cbehavior%2Ccultivated%2Cestablishment_means%2Coccurrence_status%2Cpreparations%2Cdisposition%2Cassociated_media%2Cassociated_references%2Cassociated_sequences%2Cassociated_taxa%2Cother_catalog_numbers%2Coccurrence_remarks%2Cindividual_id%2Cid%2Clocation_id%2Chigher_geography%2Ccontinent%2Cwater_body%2Cisland_group%2Cisland%2Ccountry%2Ccountry_code%2Cstate%2Ccounty%2Cmunicipality%2Craw_locality%2Cverbatim_locality%2Cmin_elevation_d%2Cmax_elevation_d%2Celevation%2Cmin_depth_d%2Cmax_depth_d%2Clocation_according_to%2Clocation_remarks%2Clatitude%2Clongitude%2Ccoordinate_uncertainty%2Ccoordinate_precision%2Cverbatim_coordinates%2Craw_latitude%2Cverbatim_latitude%2Craw_longitude%2Cverbatim_longitude%2Craw_datum%2Cverbatim_coordinate_system%2Cverbatim_srs%2Cfootprint_wkt%2Cfootprint_srs%2Cgeoreferenced_by%2Cgeoreferenced_date%2Cgeoreference_protocol%2Cgeoreference_sources%2Cgeoreference_verification_status%2Cgeoreference_remarks%2Ctaxon_id%2Cscientific_name_id%2Ctaxon_concept_lsid%2Craw_taxon_name%2Ctaxon_name%2Caccepted_name_usage%2Cparent_name_usage%2Coriginal_name_usage%2Cname_published_in%2Chigher_classification%2Ckingdom%2Cphylum%2Cclass%2Corder%2Cfamily%2Cgenus%2Csubgenus%2Cspecific_epithet%2Cinfraspecific_epithet%2Crank%2Ccommon_name%2Cnomenclatural_code%2Ctaxonomic_status%2Cnomenclatural_status%2Ctaxon_remarks%2Cspecies%2Cel754%2Cel603%2Cel1004%2Cel855%2Cel704%2Cel830%2Cel880%2Cel595%2Cel779%2Cel2094%2Cel736%2Cel772%2Cel722%2Cel729%2Cel1041%2Cel873%2Cel812%2Cel819%2Cel898%2Cel837%2Cel2099%2Cel848%2Cel891%2Cel790%2Cel768%2Cel765%2Cel711%2Cel1018%2Cel797%2Cel718%2Cel844%2Cel887%2Cel1046%2Cel894%2Cel2043%2Cel725%2Cel671%2Cel1013%2Cel761%2Cel884%2Cel591%2Cel715%2Cel841%2Cel1031%2Cel834%2Cel1036%2Cel750%2Cel1074%2Cel858%2Cel708%2Cel783%2Cel674%2Cel793%2Cel642%2Cel852%2Cel1078%2Cel675%2Cel1040%2Cel1073%2Cel2016%2Cel682%2Cel599%2Cel667%2Cel1032%2Cel1079%2Cel739%2Cel999%2Cel740%2Cel789%2Cel1005%2Cel827%2Cel1037%2Cel726%2Cel862%2Cel949%2Cel895%2Cel1000%2Cel1003%2Cel2089%2Cel1009%2Cel2101%2Cel743%2Cel786%2Cel2102%2Cel607%2Cel733%2Cel1008%2Cel776%2Cel829%2Cel737%2Cel1017%2Cel645%2Cel771%2Cel888%2Cel594%2Cel2093%2Cel778%2Cel863%2Cel712%2Cel769%2Cel996%2Cel1026%2Cel822%2Cel652%2Cel955%2Cel672%2Cel2126%2Cel654%2Cel1033%2Cel1077%2Cel659%2Cel681%2Cel811%2Cel950%2Cel744%2Cel870%2Cel815%2Cel764%2Cel877%2Cel2044%2Cel2095%2Cel798%2Cel948%2Cel791%2Cel1045%2Cel661%2Cel890%2Cel868%2Cel831%2Cel1015%2Cel2042%2Cel1047%2Cel705%2Cel751%2Cel758%2Cel851%2Cel792%2Cel808%2Cel2091%2Cel876%2Cel843%2Cel666%2Cel816%2Cel810%2Cel1019%2Cel809%2Cel2122%2Cel849%2Cel757%2Cel732%2Cel1028%2Cel883%2Cel752%2Cel2119%2Cel785%2Cel724%2Cel850%2Cel1024%2Cel1056%2Cel869%2Cel660%2Cel836%2Cel646%2Cel995%2Cel1022%2Cel717%2Cel889%2Cel600%2Cel1020%2Cel673%2Cel823%2Cel653%2Cel856%2Cel662%2Cel586%2Cel947%2Cel2018%2Cel745%2Cel1025%2Cel763%2Cel788%2Cel814%2Cel1039%2Cel795%2Cel1080%2Cel680%2Cel839%2Cel669%2Cel1034%2Cel644%2Cel770%2Cel1043%2Cel2092%2Cel777%2Cel655%2Cel2097%2Cel651%2Cel1016%2Cel878%2Cel731%2Cel709%2Cel835%2Cel828%2Cel774%2Cel871%2Cel658%2Cel738%2Cel864%2Cel781%2Cel821%2Cel954%2Cel784%2Cel1011%2Cel997%2Cel867%2Cel716%2Cel749%2Cel993%2Cel994%2Cel817%2Cel825%2Cel951%2Cel2088%2Cel1044%2Cel665%2Cel1001%2Cel760%2Cel759%2Cel885%2Cel824%2Cel857%2Cel706%2Cel1035%2Cel842%2Cel875%2Cel601%2Cel2100%2Cel832%2Cel596%2Cel723%2Cel756%2Cel882%2Cel593%2Cel807%2Cel647%2Cel773%2Cel1002%2Cel720%2Cel892%2Cel713%2Cel753%2Cel799%2Cel710%2Cel766%2Cel2104%2Cel1006%2Cel989%2Cel1007%2Cel2103%2Cel813%2Cel872%2Cel728%2Cel796%2Cel787%2Cel879%2Cel1042%2Cel1038%2Cel881%2Cel746%2Cel730%2Cel721%2Cel755%2Cel1072%2Cel998%2Cel719%2Cel845%2Cel762%2Cel2017%2Cel670%2Cel2121%2Cel840%2Cel2098%2Cel1029%2Cel865%2Cel735%2Cel794%2Cel1030%2Cel609%2Cel861%2Cel957%2Cel1014%2Cel602%2Cel854%2Cel741%2Cel818%2Cel838%2Cel1010%2Cel2090%2Cel668%2Cel748%2Cel874%2Cel1012%2Cel775%2Cel598%2Cel683%2Cel2096%2Cel615%2Cel648%2Cel826%2Cel952%2Cel859%2Cel650%2Cel1023%2Cel1027%2Cel734%2Cel1081%2Cel649%2Cel608%2Cel860%2Cel767%2Cel893%2Cel616%2Cel742%2Cel597%2Cel643%2Cel714%2Cel886%2Cel806%2Cel676%2Cel747%2Cel820%2Cel656%2Cel782%2Cel727%2Cel853%2Cel1021%2Cel663%2Cel866%2Cel833%2Cel707%2Cel992%2Cel899%2Cel610%2Cel1055&extra=&reasonTypeId=7&sourceTypeId=0&qa=includeall&dwcHeaders=true",
      "esc": "\"",
      "extra": "",
      "facet": false,
      "facets": [
        "data_resource_uid"
      ],
      "fields": "rowkey,language,license,rightsholder,access_rights,bibliographic_citation,institution_id,collection_id,dataset_id,institution_code,collection_code,dataset_name,owner_institution_code,basis_of_record,dynamic_properties,provenance,rights,source,occurrence_id,catalogue_number,record_number,collector,individual_count,organism_quantity,organism_quantity_type,raw_sex,life_stage,reproductive_condition,behavior,cultivated,establishment_means,occurrence_status,preparations,disposition,associated_media,associated_references,associated_sequences,associated_taxa,other_catalog_numbers,occurrence_remarks,individual_id,id,location_id,higher_geography,continent,water_body,island_group,island,country,country_code,state,county,municipality,raw_locality,verbatim_locality,min_elevation_d,max_elevation_d,elevation,min_depth_d,max_depth_d,location_according_to,location_remarks,latitude,longitude,coordinate_uncertainty,coordinate_precision,verbatim_coordinates,raw_latitude,verbatim_latitude,raw_longitude,verbatim_longitude,raw_datum,verbatim_coordinate_system,verbatim_srs,footprint_wkt,footprint_srs,georeferenced_by,georeferenced_date,georeference_protocol,georeference_sources,georeference_verification_status,georeference_remarks,taxon_id,scientific_name_id,taxon_concept_lsid,raw_taxon_name,taxon_name,accepted_name_usage,parent_name_usage,original_name_usage,name_published_in,higher_classification,kingdom,phylum,class,order,family,genus,subgenus,specific_epithet,infraspecific_epithet,rank,common_name,nomenclatural_code,taxonomic_status,nomenclatural_status,taxon_remarks,species,el754,el603,el1004,el855,el704,el830,el880,el595,el779,el2094,el736,el772,el722,el729,el1041,el873,el812,el819,el898,el837,el2099,el848,el891,el790,el768,el765,el711,el1018,el797,el718,el844,el887,el1046,el894,el2043,el725,el671,el1013,el761,el884,el591,el715,el841,el1031,el834,el1036,el750,el1074,el858,el708,el783,el674,el793,el642,el852,el1078,el675,el1040,el1073,el2016,el682,el599,el667,el1032,el1079,el739,el999,el740,el789,el1005,el827,el1037,el726,el862,el949,el895,el1000,el1003,el2089,el1009,el2101,el743,el786,el2102,el607,el733,el1008,el776,el829,el737,el1017,el645,el771,el888,el594,el2093,el778,el863,el712,el769,el996,el1026,el822,el652,el955,el672,el2126,el654,el1033,el1077,el659,el681,el811,el950,el744,el870,el815,el764,el877,el2044,el2095,el798,el948,el791,el1045,el661,el890,el868,el831,el1015,el2042,el1047,el705,el751,el758,el851,el792,el808,el2091,el876,el843,el666,el816,el810,el1019,el809,el2122,el849,el757,el732,el1028,el883,el752,el2119,el785,el724,el850,el1024,el1056,el869,el660,el836,el646,el995,el1022,el717,el889,el600,el1020,el673,el823,el653,el856,el662,el586,el947,el2018,el745,el1025,el763,el788,el814,el1039,el795,el1080,el680,el839,el669,el1034,el644,el770,el1043,el2092,el777,el655,el2097,el651,el1016,el878,el731,el709,el835,el828,el774,el871,el658,el738,el864,el781,el821,el954,el784,el1011,el997,el867,el716,el749,el993,el994,el817,el825,el951,el2088,el1044,el665,el1001,el760,el759,el885,el824,el857,el706,el1035,el842,el875,el601,el2100,el832,el596,el723,el756,el882,el593,el807,el647,el773,el1002,el720,el892,el713,el753,el799,el710,el766,el2104,el1006,el989,el1007,el2103,el813,el872,el728,el796,el787,el879,el1042,el1038,el881,el746,el730,el721,el755,el1072,el998,el719,el845,el762,el2017,el670,el2121,el840,el2098,el1029,el865,el735,el794,el1030,el609,el861,el957,el1014,el602,el854,el741,el818,el838,el1010,el2090,el668,el748,el874,el1012,el775,el598,el683,el2096,el615,el648,el826,el952,el859,el650,el1023,el1027,el734,el1081,el649,el608,el860,el767,el893,el616,el742,el597,el643,el714,el886,el806,el676,el747,el820,el656,el782,el727,el853,el1021,el663,el866,el833,el707,el992,el899,el610,el1055",
      "file": "Batch_17",
      "fileType": "csv",
      "fl": "occurrence_date,country,geospatial_kosher,year,point-0.01,data_resource,taxonomic_kosher,lat_long,record_number,species_guid,state_conservation,occurrence_year,genus_guid,taxon_concept_lsid,occurrence_remarks,point-0.1,rank,data_provider,user_assertions,id,state,assertions,common_name,raw_common_name,order,longitude,basis_of_record,collection_uid,image_url,location_remarks,point-1,sensitive,point-0.0001,identification_verification_status,country_code,license,collectors,month,genus,occurrence_id,ibra,lft,species_group,subspecies,occurrence_details,collection_name,collection_code,rank_id,raw_taxon_name,occurrence_date_end_dt,data_resource_uid,data_hub,latitude,data_provider_uid,type_status,institution_name,collector,imcra,institution_uid,subspecies_guid,rights,taxon_name,class,rgt,grid_ref,catalogue_number,aust_conservation,data_hub_uid,names_and_lsid,point-0.001,photographer_s,coordinate_uncertainty,all_image_url,kingdom,institution_code,raw_type_status,places,multimedia,phylum,species,raw_basis_of_record,family",
      "flimit": 30,
      "foffset": 0,
      "formattedQuery": "(raw_name:\"Chlamydera cerviniventris\" OR raw_name:\"Grallina cyanoleuca\")",
      "fprefix": "",
      "fq": [],
      "fsort": "",
      "gk": false,
      "hubName": "Atlas of Living Australia",
      "includeMisc": false,
      "includeMultivalues": false,
      "layersServiceUrl": "",
      "mintDoi": true,
      "pageSize": 0,
      "q": "qid:1582507139142",
      "qa": "includeall",
      "qc": "",
      "reason": "",
      "reasonTypeId": 7,
      "searchUrl": "https://biocache.ala.org.au/occurrences/search?q=qid%3A1582507139142",
      "sep": ",",
      "sort": "score",
      "sourceTypeId": 0,
      "start": 0,
      "startIndex": 0,
      "urlParams": "?q=qid%3A1582507139142",
      "wkt": ""
    },
    "startDate": {
      "date": 24,
      "day": 1,
      "hours": 12,
      "minutes": 19,
      "month": 1,
      "seconds": 15,
      "time": 1582507155362,
      "timezoneOffset": -660,
      "year": 120
    },
    "startDateString": "Mon Feb 24 12:19:15 AEDT 2020",
    "startTime": 1582507155362,
    "totalRecords": 874696,
    "uniqueId": "319810e3-9792-3933-a9fb-a4fde4c534b8-1582507155362",
    "cancelURL": "https://biocache-ws.ala.org.au/ws/occurrences/offline/cancel/319810e3-9792-3933-a9fb-a4fde4c534b8-1582507155362?apiKey=567776b9-d184-4276-afc2-6ece17176d7c"
  }
]
```

**Comment by brucehyslop** [comment]
Unable to replicate the issue with the offline download `q=qid%3A1582507139142`

If appears the cause of the `IndexOutOfBoundsException` is because an empty array is returned from [Bulk lookup by GUID - https://bie-ws.ala.org.au/ws/species/guids/bulklookup  ](https://api.ala.org.au/#ws110) 

The other list sizes are checked prior to access.
https://github.com/AtlasOfLivingAustralia/biocache-service/blob/af0a5a6427073ebd45a62495a502c870291d38a1/src/main/java/au/org/ala/biocache/service/SpeciesLookupRestService.java#L207

**Comment by ansell** [comment]
Changing to check the bounds on the two lists that it is trying to merge is a good fix in itself. The previous code was effectively presuming that all of the guids matched, which was causing many issues in practice.

**Comment by brucehyslop** [comment]
If a guid does not match an `null` value is return in the result list, so the guid list and the results sizes should match (in theory).

**Comment by nickdos** [comment]
@brucehyslop is there an example query we can use to test this fix?

**Comment by nickdos** [comment]
I've tested with the query:

https://biocache-test.ala.org.au/occurrences/search?q=(raw_name%3A%22Chlamydera%20cerviniventris%22%20OR%20raw_name%3A%22Grallina%20cyanoleuca%22)

 and it worked but no DOI was minted. Not sure that triggers the bug however...

**Comment by ansell** [comment]
There is another separate `SpeciesLookupRestService` method generating `IndexOutOfBoundsException`, so I will open a new issue for that. Don't get it confused with this one as it has a different stacktrace.
