### ISSUE TITLE
Debug broken PersistentQueueDAOTest on travis

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#400]
The `PersistentQueueDAOTest` failed on Travis in build 641. https://travis-ci.org/AtlasOfLivingAustralia/biocache-service/builds/583409105 The output is:

The relevant commit added a single line to the i18n properties file, so it was definitely not a direct cause. https://github.com/AtlasOfLivingAustralia/biocache-service/commit/f52970bba443303acef5517d0f1cc43034982d2d

```
[INFO] Running au.org.ala.biocache.dao.PersistentQueueDAOTest

BEFORE...

test add

[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /home/travis/build/AtlasOfLivingAustralia/biocache-service/target/surefire-reports/2019-09-10T23-11-17_878-jvmRun1.dumpstream

[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.565 s <<< FAILURE! - in au.org.ala.biocache.dao.PersistentQueueDAOTest

[ERROR] testQueue  Time elapsed: 0.565 s  <<< FAILURE!

java.lang.AssertionError: expected:<2> but was:<0>

	at org.junit.Assert.fail(Assert.java:88)

	at org.junit.Assert.failNotEquals(Assert.java:834)

	at org.junit.Assert.assertEquals(Assert.java:645)

	at org.junit.Assert.assertEquals(Assert.java:631)

	at au.org.ala.biocache.dao.PersistentQueueDAOTest.testQueue(PersistentQueueDAOTest.java:82)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)

	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)

	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ansell** [comment]
Testing on desktop revealed that the test failed but didn't reveal why. The one-line change to the i18n file has been reverted so that we can release today.

**Comment by ansell** [comment]
This is a duplicate of issue #422
