### ISSUE TITLE
Download error due to NoSuchElementException (None.get) during sampling intersection

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#433]
A user contacted us after their download failed. The logs showed the following error, which is unexpected as I thought that we were still sampling all layers into the solr index and not doing on-demand sampling. However, in the near future we are planning to remove layers from solr purpose for cost purposes, and this code may be used again at that point.

```
java.util.concurrent.ExecutionException: java.util.NoSuchElementException: None.get
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1471)
	at sun.reflect.GeneratedMethodAccessor270.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy54.writeResultsFromIndexToStream(Unknown Source)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:577)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1240)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at au.org.ala.biocache.util.LayersStore.samplingStart(LayersStore.scala:169)
	at au.org.ala.biocache.util.LayersStore.sample(LayersStore.scala:48)
	at au.org.ala.biocache.dao.SearchDAOImpl.intersectResults(SearchDAOImpl.java:1583)
	at au.org.ala.biocache.dao.SearchDAOImpl.processQueryResults(SearchDAOImpl.java:1603)
	at au.org.ala.biocache.dao.SearchDAOImpl.access$200(SearchDAOImpl.java:95)
	at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1412)
	at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1380)
	... 4 more
```

The `biocache-service` query was:

```
/ws/occurrences/offline/download?hubName=Atlas+of+Living+Australia&file=records-2020-02-27&mintDoi=true&reasonTypeId=4&layersServiceUrl=https%3A%2F%2Fspatial.ala.org.au%2Fws&searchUrl=https%3A%2F%2Fbiocache.ala.org.au%2Foccurrences%2Fsearch%3Fq%3Dqid%3A1582807908388&fileType=csv&customHeader=NRM+Regions+2017+%28Qld+2019%29%2CNRM+Regions+2017%2CGlobal+200+priority+ecoregions+-+Terrestrial%2CCAPAD+2014+Terrestrial%2CCAPAD+2014+Terrestrial+%28Classes%29%2CCAPAD+2016+Terrestrial&qa=none&sourceTypeId=0&email=example%40example.org&doiDisplayUrl=https%3A%2F%2Fbiocache.ala.org.au%2Fdownload%2Fdoi%3Fdoi%3D&extra=cl10947%2Ccl10930%2Ccl2084%2Ccl2079%2Ccl12079%2Ccl10944&q=qid:1582807908388
```

**Comment by ansell** [comment]
Refs ticket 75426 in freshdesk

**Comment by djtfmartin** [comment]
Closing historic issue. If this is still a problem, please reopen.
