### ISSUE TITLE
Download fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/biocache-service#524]
```
020-09-08 09:51:29,460 [biocachedownload-pool-5000000-RECORDS_INDEX-0] INFO
au.org.ala.biocache.service.DownloadService  (DownloadService.java:1290) - Starting to
download the offline request: DownloadDetailsDTO [downloadType=RECORDS_INDEX,
startDate=Tue Sep 08 09:51:29 AEST 2020, lastUpdate=Tue Sep 08 09:51:29 AEST 2020,
totalRecords=1550164, recordsDownloaded=0, downloadParams=?q=species_list_uid%3Adr656,
ipAddress=127.0.0.1, email=cor..per@csiro.au,
requestParams=q=species_list_uid:dr656&start=0&pageSize=0&sort=score&dir=asc&qc=&fl=occurrence_date,country,geospatial_kosher,year,point-0.01,data_resource,taxonomic_kosher,lat_long,record_number,species_guid,state_conservation,occurrence_year,genus_guid,taxon_concept_lsid,occurrence_remarks,point-0.1,rank,data_provider,user_assertions,id,state,assertions,common_name,raw_common_name,order,longitude,basis_of_record,collection_uid,image_url,location_remarks,point-1,sensitive,point-0.0001,identification_verification_status,country_code,license,collectors,month,genus,occurrence_id,ibra,lft,species_group,subspecies,occurrence_details,collection_name,collection_code,rank_id,raw_taxon_name,occurrence_date_end_dt,data_resource_uid,data_hub,latitude,data_provider_uid,type_status,institution_name,collector,imcra,institution_uid,subspecies_guid,rights,taxon_name,class,rgt,grid_ref,catalogue_number,aust_conservation,data_hub_uid,names_and_lsid,point-0.001,photographer_s,coordinate_uncertainty,all_image_url,kingdom,institution_code,raw_type_status,places,multimedia,phylum,species,raw_basis_of_record,family&formattedQuery=species_list_uid:dr656&facet=false&email=corinna.paeper@csiro.au&reason=&file=records-2020-09-08&fields=&extra=dr656&reasonTypeId=10&sourceTypeId=0&qa=none]

2020-09-08 09:51:51,298 [biocachedownload-pool-5000000-RECORDS_INDEX-0] ERROR
au.org.ala.biocache.service.DownloadService  (DownloadService.java:1422) - Error in
offline download, sending email. download path:
/data/biocache-download/biocache-download/89d7442f-2b34-3607-bf49-73a0fa0638ce/1599522689146/records-2020-09-08.zip
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 340, Size: 339
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1473)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
at com.sun.proxy.$Proxy63.writeResultsFromIndexToStream(Unknown Source)
at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:592)
at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1314)
at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1284)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 340, Size: 339
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at au.org.ala.biocache.service.ListsService.find(ListsService.java:305)
at au.org.ala.biocache.service.ListsService.getKvpValue(ListsService.java:288)
at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
at au.org.ala.biocache.service.ListsService$$EnhancerBySpringCGLIB$$768e1d91.getKvpValue(<generated>)
at au.org.ala.biocache.dao.SearchDAOImpl.processQueryResults(SearchDAOImpl.java:1672)
at au.org.ala.biocache.dao.SearchDAOImpl.access$200(SearchDAOImpl.java:95)
at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1414)
at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1382)
... 4 more
```

**Comment by ansell** [comment]
This issue also occurred yesterday and caused some failed downloads.

**Comment by ansell** [comment]
@brucehyslop Will the change for this also fix the following slightly different issue directly in `ListsService.getKvpValue` or should I create a new issue for it:

```
2020-10-22 17:23:12,808 [biocachedownload-pool-500000-RECORDS_INDEX-0] ERROR au.org.ala.biocache.service.DownloadService  (DownloadService.java:1496) - Error in offline download, sending email. download path: /data/biocache-download/biocache-download/fa9d6ebc-4890-3841-9450-bb52a7e5b409/1603347571325/records-2020-10-22.zip
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:1473)
	at sun.reflect.GeneratedMethodAccessor411.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy60.writeResultsFromIndexToStream(Unknown Source)
	at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:622)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1380)
	at au.org.ala.biocache.service.DownloadService$DownloadCreatorImpl$1.call(DownloadService.java:1350)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at au.org.ala.biocache.service.ListsService.getKvpValue(ListsService.java:290)
	at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at au.org.ala.biocache.service.ListsService$$EnhancerBySpringCGLIB$$12304e43.getKvpValue(<generated>)
	at au.org.ala.biocache.dao.SearchDAOImpl.processQueryResults(SearchDAOImpl.java:1672)
	at au.org.ala.biocache.dao.SearchDAOImpl.access$200(SearchDAOImpl.java:95)
	at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1414)
	at au.org.ala.biocache.dao.SearchDAOImpl$4.call(SearchDAOImpl.java:1382)
	... 4 more
2020-10-22 17:23:12,814 [biocachedownload-pool-500000-RECORDS_INDEX-0] INFO au.org.ala.biocache.dao.JsonPersistentQueueDAOImpl  (JsonPersistentQueueDAOImpl.java:236) - Deleting /data/cache/downloads/offline1603347571325.json true
```

**Comment by brucehyslop** [comment]
The issue above is a new issue, the `IndexOutOfBoundsException` is am incorrect index into the `Kvp.value` List<String>.

**Comment by nickdos** [comment]
Can't easily test for this, so once deployed, logs will clearly show if this is still an issue.

**Comment by nickdos** [comment]
Deployed to prod - need to watch for errors in log (thus `waiting for` status)

**Comment by nickdos** [comment]
Logs are clear - see related issue #557 .
