### ISSUE TITLE
Intermittent failure in Cassandra3PersistenceManager

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#553]
The following failure appears in `journalctl -xe` on `biocache-service-2.5.1` instances at an intermittent interval, but not sure what the cause is yet.

Opening an issue here even though the stacktrace is from `biocache-store` because I haven't noticed the issue there, but we could move it there:

```
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]: java.lang.IndexOutOfBoundsException: Index: 416, Size: 416
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at java.util.ArrayList.rangeCheck(ArrayList.java:659)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at java.util.ArrayList.get(ArrayList.java:435)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.datastax.driver.core.ArrayBackedRow.getValue(ArrayBackedRow.java:75)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.datastax.driver.core.AbstractGettableByIndexData.getString(AbstractGettableByIndexData.java:208)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.datastax.driver.core.AbstractGettableData.getString(AbstractGettableData.java:29)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.datastax.driver.core.AbstractGettableData.getString(AbstractGettableData.java:134)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$get$1.apply(Cassandra3PersistenceManager.scala:161)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.persistence.Cassandra3PersistenceManager$$anonfun$get$1.apply(Cassandra3PersistenceManager.scala:160)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at scala.collection.Iterator$class.foreach(Iterator.scala:727)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.persistence.Cassandra3PersistenceManager.get(Cassandra3PersistenceManager.scala:160)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.dao.OccurrenceDAOImpl.getAllVersionsByRowKey(OccurrenceDAOImpl.scala:76)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.Store$.getComparisonByUuid(Store.scala:84)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.Store.getComparisonByUuid(Store.scala)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.util.OccurrenceUtils.getComparisonByUuid(OccurrenceUtils.java:52)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.web.OccurrenceController.showOccurrence(OccurrenceController.java:1258)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at sun.reflect.GeneratedMethodAccessor804.invoke(Unknown Source)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at java.lang.reflect.Method.invoke(Method.java:498)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at au.org.ala.biocache.web.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:33)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Oct 19 17:01:33 aws-biocache-service-20-04-prod-2 tomcat9[570]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
```

This breaks occurrence record view that is still pointed at Cassandra:

```
https://aws-biocache-service-20-04-prod-2.ala.org.au/ws/occurrence/compare/879323c7-cffb-40c3-9e33-7f621d5a3c72
```

The document returned is the following:

```
{
"message": "Index: 416, Size: 416", "errorType": "Server error"
}
```

**Comment by sadeghim** [comment]
@adam-collins, I guess this happened  when I was doing some updates on cass DB. one of the updates was dropping a column from `occ.occ` and never thought that biocache-service will keep the columns somewhere and then get out of sync.
