### ISSUE TITLE
Encode characters before querying specieslists

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/biocache-service#554]
The following URISyntaxException (due to an SQLi attempt) indicates that we need to encode characters before creating the specieslists query URL. Specieslists should then handle the queries as expected based on its SQLi protections:

```
2020-10-20 09:09:09,931 [speciesKvp Cache Refresh Timer] ERROR au.org.ala.biocache.service.DownloadService  (ListsService.java:188) - failed to get species list kvp for list: 5) AND (9442=9442
java.net.URISyntaxException: Illegal character in path at index 47: https://lists.ala.org.au/ws/speciesListItems/5) AND (9442=9442?includeKVP=true
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at au.org.ala.biocache.service.ListsService.getKvp(ListsService.java:162)
        at au.org.ala.biocache.service.ListsService$$FastClassBySpringCGLIB$$4eb198f1.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at com.googlecode.ehcache.annotations.resolver.ThreadLocalCacheEntryFactory.createEntry(ThreadLocalCacheEntryFactory.java:36)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.createEntry(RefreshingCacheEntryFactory.java:60)
        at com.googlecode.ehcache.annotations.RefreshingCacheEntryFactory.updateEntryValue(RefreshingCacheEntryFactory.java:44)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refreshElement(SelfPopulatingCache.java:259)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache.refreshElement(RefreshingSelfPopulatingCache.java:143)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:153)
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.refresh(SelfPopulatingCache.java:106)
        at com.googlecode.ehcache.annotations.RefreshingSelfPopulatingCache$2.run(RefreshingSelfPopulatingCache.java:100)
        at com.googlecode.ehcache.annotations.support.TimerTaskSchedulerAdapter$1.run(TimerTaskSchedulerAdapter.java:42)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

**Comment by ansell** [comment]
Oops, closing this, it is a duplicate of #372
