### ISSUE TITLE
Restarting biocache-service is (possibly) not restarting downloads interrupted

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/biocache-service#901]
This is speculation on errors in the log.

When biocache-service downloads are interrupted by a shutdown, a user's details, e.g. email and roles, are not properly saved and recalled. 

The error is
```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at java.base/java.util.ArrayList.batchRemove(ArrayList.java:848)
        at java.base/java.util.ArrayList.retainAll(ArrayList.java:843)
        at au.org.ala.biocache.service.DownloadService.getSensitiveFq(DownloadService.java:1065)
        at au.org.ala.biocache.dao.SearchDAOImpl.writeResultsFromIndexToStream(SearchDAOImpl.java:603)
...
        at au.org.ala.biocache.service.DownloadService.writeQueryToStream(DownloadService.java:435)
        at au.org.ala.biocache.service.DownloadService$DownloadRunnable.run(DownloadService.java:1195)
```

**Comment by adam-collins** [comment]
Fixed 2 issues:
- Some environments were unable to read the json files used to recover downloads interrupted by a restart.
- If downloads were re-added to the queue, they would fail and send an email "something went wrong".
